import json
import tempfile
import unittest
from pathlib import Path

from helpers import (BRAINSTORM_FOLLOWUP, BRAINSTORM_R1, CRITIQUE_FOLLOWUP,
                     CRITIQUE_R1, DECIDE_R1, SOLVE_FOLLOWUP, SOLVE_FOLLOWUP_REVISE,
                     SOLVE_FOLLOWUP_UNCHANGED, SOLVE_R1, SOLVE_R1_RESULT, run)


class LedgerTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.session = Path(self.tmp.name)

    def tearDown(self):
        self.tmp.cleanup()

    def seat(self, rnd, letter, text):
        sub = "select" if rnd == "select" else f"round-{rnd}"
        path = self.session / "leg-1" / sub / f"{letter}.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    def ledger(self, rnd, fmt):
        return run(["ledger", "--session", str(self.session), "--leg", "1",
                    "--round", str(rnd), "--format", fmt])

    def items(self):
        return json.loads((self.session / "leg-1/items.json").read_text(encoding="utf-8"))

    def ledger_md(self, rnd=1):
        return (self.session / f"leg-1/ledger-{rnd}.md").read_text(encoding="utf-8")

    def test_round_one_prefixes_ids(self):
        self.seat(1, "A", BRAINSTORM_R1)
        self.seat(1, "B", BRAINSTORM_R1)
        code, out = self.ledger(1, "brainstorm-r1")
        self.assertEqual(code, 0, out)
        self.assertEqual([i["id"] for i in self.items()],
                         ["A-I1", "A-I2", "A-I3", "A-I4", "A-WILDCARD",
                          "B-I1", "B-I2", "B-I3", "B-I4", "B-WILDCARD"])
        md = self.ledger_md()
        self.assertIn("## Items (generated by hive.py; do not edit)", md)
        self.assertIn("A-I2 [novelty: high] [effort: mid] Repair night:", md)
        self.assertTrue(md.endswith("## Moderator\n\n"))

    def test_moderator_section_survives_regeneration(self):
        self.seat(1, "A", BRAINSTORM_R1)
        self.ledger(1, "brainstorm-r1")
        path = self.session / "leg-1/ledger-1.md"
        mod = "## Moderator\n\nK1 Evening use: A-I1, A-I4\nCrux: none yet.  \n"
        path.write_text(path.read_text(encoding="utf-8").replace("## Moderator\n\n", mod),
                        encoding="utf-8")
        self.seat(1, "B", BRAINSTORM_R1)
        self.ledger(1, "brainstorm-r1")
        text = self.ledger_md()
        self.assertTrue(text.endswith(mod))
        self.assertIn("### Seat B", text)

    def test_rerun_is_idempotent(self):
        self.seat(1, "A", BRAINSTORM_R1)
        self.ledger(1, "brainstorm-r1")
        self.ledger(1, "brainstorm-r1")
        self.assertEqual(len(self.items()), 5)

    def test_builds_and_dangling_references(self):
        self.seat(1, "B", BRAINSTORM_R1)
        self.ledger(1, "brainstorm-r1")
        self.seat(2, "C", BRAINSTORM_FOLLOWUP.replace("B-I2", "B-I9"))
        code, out = self.ledger(2, "brainstorm-followup")
        self.assertEqual(code, 1)
        self.assertIn("dangling: leg-1 round 2: C cites B-I9", out)
        self.assertIn("C-N1", [i["id"] for i in self.items()])

    def test_new_line_becomes_item(self):
        self.seat(1, "B", BRAINSTORM_R1)
        self.ledger(1, "brainstorm-r1")
        self.seat(2, "C", BRAINSTORM_FOLLOWUP.replace("NEW: none", "NEW: Seed library: Lend seeds in spring."))
        self.assertEqual(self.ledger(2, "brainstorm-followup")[0], 0)
        self.assertIn("C-NEW", [i["id"] for i in self.items()])

    def test_decide_new_option_gets_next_o_number(self):
        self.seat(1, "A", DECIDE_R1)
        self.seat(1, "B", DECIDE_R1.replace("NEW Rent and invest the difference", "NEW Buy with a friend"))
        code, out = self.ledger(1, "decide-r1")
        self.assertEqual(code, 0, out)
        options = [(i["id"], i["seat"]) for i in self.items() if i["kind"] == "option"]
        self.assertEqual(options, [("O3", "A"), ("O4", "B")])
        self.assertIn("O4 (NEW from B)", self.ledger_md())

    def test_refuses_invalid_seat_file(self):
        self.seat(1, "A", BRAINSTORM_R1.replace("WILDCARD:", "WILD:"))
        code, out = self.ledger(1, "brainstorm-r1")
        self.assertEqual(code, 1)
        self.assertIn("A.md", out)
        self.assertFalse((self.session / "leg-1/items.json").exists())

    def test_change_lines_for_followups(self):
        self.seat(1, "B", CRITIQUE_R1)
        self.ledger(1, "critique-r1")
        self.seat(2, "A", CRITIQUE_FOLLOWUP)
        code, out = self.ledger(2, "critique-followup")
        self.assertEqual(code, 0, out)
        self.assertIn("A: POSITION changed; BECAUSE B-C1", out)

    def test_user_items_are_known(self):
        self.seat(1, "B", CRITIQUE_R1)
        self.ledger(1, "critique-r1")
        (self.session / "leg-1/user-items.json").write_text('["U1"]', encoding="utf-8")
        self.seat(2, "A", CRITIQUE_FOLLOWUP.replace("B-C1: Replays", "U1: Replays"))
        self.assertEqual(self.ledger(2, "critique-followup")[0], 0)

    def test_moderator_m_areas_are_known(self):
        self.seat(1, "B", CRITIQUE_R1)
        self.ledger(1, "critique-r1")
        path = self.session / "leg-1/ledger-1.md"
        path.write_text(path.read_text(encoding="utf-8") + "M1 Contracts: B-C1\n", encoding="utf-8")
        self.seat(2, "A", CRITIQUE_FOLLOWUP.replace("B-C2: A managed", "M1: A managed"))
        self.assertEqual(self.ledger(2, "critique-followup")[0], 0)

    def test_no_seat_files_exits_2(self):
        self.assertEqual(self.ledger(1, "brainstorm-r1")[0], 2)

    def test_repeated_local_ids_are_renumbered(self):
        self.seat(1, "B", BRAINSTORM_R1)
        self.ledger(1, "brainstorm-r1")
        self.seat(2, "C", BRAINSTORM_FOLLOWUP)
        self.ledger(2, "brainstorm-followup")
        self.seat(3, "C", BRAINSTORM_FOLLOWUP)
        code, out = self.ledger(3, "brainstorm-followup")
        self.assertEqual(code, 0, out)
        third = [(i["id"], i["local"]) for i in self.items() if i["round"] == "3"]
        self.assertEqual(third, [("C-N3", "N1"), ("C-N4", "N2")])

    def test_new_leg_does_not_reuse_ids(self):
        self.seat(1, "B", CRITIQUE_R1)
        self.ledger(1, "critique-r1")
        path = self.session / "leg-2/round-1/B.md"
        path.parent.mkdir(parents=True)
        path.write_text(CRITIQUE_R1, encoding="utf-8")
        code, out = run(["ledger", "--session", str(self.session), "--leg", "2", "--round", "1",
                         "--format", "critique-r1"])
        self.assertEqual(code, 0, out)
        leg2 = json.loads((self.session / "leg-2/items.json").read_text(encoding="utf-8"))
        self.assertEqual([i["id"] for i in leg2], ["B-C4", "B-C5", "B-C6"])

    def test_rerun_keeps_new_option_number_after_later_leg(self):
        self.seat(1, "A", DECIDE_R1)
        self.ledger(1, "decide-r1")
        later = self.session / "leg-2/round-1/B.md"
        later.parent.mkdir(parents=True)
        later.write_text(DECIDE_R1.replace("NEW Rent and invest the difference",
                                           "O3 Rent and invest the difference"), encoding="utf-8")
        code, out = run(["ledger", "--session", str(self.session), "--leg", "2", "--round", "1",
                         "--format", "decide-r1"])
        self.assertEqual(code, 0, out)
        self.assertEqual(self.ledger(1, "decide-r1")[0], 0)
        self.assertEqual([i["id"] for i in self.items() if i["kind"] == "option"], ["O3"])

    def test_new_options_are_unique_across_legs(self):
        self.seat(1, "A", DECIDE_R1)
        self.ledger(1, "decide-r1")
        later = self.session / "leg-2/round-1/B.md"
        later.parent.mkdir(parents=True)
        later.write_text(DECIDE_R1, encoding="utf-8")
        run(["ledger", "--session", str(self.session), "--leg", "2", "--round", "1", "--format", "decide-r1"])
        leg2 = json.loads((self.session / "leg-2/items.json").read_text(encoding="utf-8"))
        self.assertEqual([i["id"] for i in leg2 if i["kind"] == "option"], ["O4"])

    def options(self):
        return [(i["id"], i["seat"]) for i in self.items() if i["kind"] == "option"]

    def test_inserting_an_earlier_seats_new_option_keeps_later_numbers(self):
        no_new = DECIDE_R1.replace("NEW Rent and invest the difference: monthly cost +, "
                                   "flexibility ++, long-term wealth + — Keeps options open.\n", "")
        self.seat(1, "A", no_new)
        self.seat(1, "B", DECIDE_R1)
        self.ledger(1, "decide-r1")
        self.assertEqual(self.options(), [("O3", "B")])
        self.seat(1, "A", DECIDE_R1)
        self.assertEqual(self.ledger(1, "decide-r1")[0], 0)
        self.assertEqual(sorted(self.options()), [("O3", "B"), ("O4", "A")])

    def test_rerun_keeps_suffixed_special_ids(self):
        self.seat(1, "A", BRAINSTORM_R1)
        self.ledger(1, "brainstorm-r1")
        later = self.session / "leg-2/round-1/A.md"
        later.parent.mkdir(parents=True)
        later.write_text(BRAINSTORM_R1, encoding="utf-8")
        leg2 = ["ledger", "--session", str(self.session), "--leg", "2", "--round", "1",
                "--format", "brainstorm-r1"]
        run(leg2)
        self.seat(1, "A", BRAINSTORM_R1.replace(
            "WILDCARD: Let teenagers run the library one evening a month.", "WILDCARD: none"))
        self.ledger(1, "brainstorm-r1")
        self.assertEqual(run(leg2)[0], 0)
        ids = [i["id"] for i in json.loads((self.session / "leg-2/items.json").read_text(encoding="utf-8"))]
        self.assertIn("A-WILDCARD2", ids)
        self.assertNotIn("A-WILDCARD", ids)

    def test_revising_an_earlier_round_reports_later_dangling_reference(self):
        self.seat(1, "B", BRAINSTORM_R1)
        self.ledger(1, "brainstorm-r1")
        self.seat(2, "C", BRAINSTORM_FOLLOWUP.replace("B-I1, B-I2", "B-I1, B-WILDCARD"))
        self.assertEqual(self.ledger(2, "brainstorm-followup")[0], 0)
        log = self.session / "seat-b.log"
        log.write_text("[User] Round 1.\n" + BRAINSTORM_R1.replace(
            "WILDCARD: Let teenagers run the library one evening a month.", "WILDCARD: none"),
            encoding="utf-8")
        code, out = run(["ingest", "--session", str(self.session), "--seat", "B", "--leg", "1",
                         "--round", "1", "--format", "brainstorm-r1", "--log", str(log), "--force"])
        self.assertEqual(code, 0, out)
        code, out = self.ledger(1, "brainstorm-r1")
        self.assertEqual(code, 1)
        self.assertIn("dangling: leg-1 round 2: C cites B-WILDCARD", out)

    def test_solve_round_one_ledger(self):
        self.seat(1, "A", SOLVE_R1)
        self.seat(1, "B", SOLVE_R1_RESULT)
        code, out = self.ledger(1, "solve-r1")
        self.assertEqual(code, 0, out)
        ids = [i["id"] for i in self.items()]
        for item in ("A-DIAGNOSIS", "A-PLAN", "A-S1", "A-S2", "A-S3", "A-R1", "B-RESULT"):
            self.assertIn(item, ids)
        self.assertFalse(any(i.endswith("-RESULT") and i.startswith("A-") for i in ids))
        kinds = {i["id"]: i["kind"] for i in self.items()}
        self.assertEqual(kinds["A-DIAGNOSIS"], "diagnosis")
        self.assertEqual(kinds["A-PLAN"], "plan")
        self.assertEqual(kinds["B-RESULT"], "result")

    def test_solve_followup_ids_plans_and_replaces(self):
        self.seat(1, "A", SOLVE_R1)
        self.seat(1, "B", SOLVE_R1_RESULT)
        self.assertEqual(self.ledger(1, "solve-r1")[0], 0)
        self.seat(2, "A", SOLVE_FOLLOWUP)
        code, out = self.ledger(2, "solve-followup")
        self.assertEqual(code, 0, out)
        self.assertNotIn("dangling:", out)
        self.assertIn("A: PLAN changed; BECAUSE B-S2", out)
        by_id = {i["id"]: i for i in self.items()}
        self.assertEqual(by_id["A-S4"]["local"], "S1")
        self.assertEqual(by_id["A-S4"]["builds_on"], ["A-S2"])
        self.assertEqual(by_id["A-S5"]["local"], "S2")
        self.assertEqual(by_id["A-S5"]["builds_on"], [])
        self.assertNotIn("A-S1", [i["id"] for i in self.items() if i["round"] == "2"])
        self.assertEqual(by_id["A-PLAN2"]["text"],
                         "Staff a second clerk for routine permits and publish the checklist.")
        self.assertEqual(by_id["A-PLAN2"]["kind"], "plan")
        self.seat(3, "A", SOLVE_FOLLOWUP_UNCHANGED)
        code, out = self.ledger(3, "solve-followup")
        self.assertEqual(code, 0, out)
        self.assertNotIn("dangling:", out)
        plans = [i["id"] for i in self.items() if i["seat"] == "A" and i["kind"] == "plan"]
        self.assertEqual(plans, ["A-PLAN", "A-PLAN2"])
        self.seat(4, "A", SOLVE_FOLLOWUP_REVISE)
        code, out = self.ledger(4, "solve-followup")
        self.assertEqual(code, 0, out)
        self.assertNotIn("dangling:", out)
        by_id = {i["id"]: i for i in self.items()}
        self.assertIn("A-PLAN3", by_id)
        self.assertEqual(by_id["A-PLAN3"]["kind"], "plan")
        revised = [i for i in self.items() if i["round"] == "4" and i["local"] == "S1"]
        self.assertEqual(len(revised), 1)
        self.assertNotEqual(revised[0]["id"], "A-S4")
        self.assertEqual(revised[0]["builds_on"], ["A-S4"])

    def test_solve_followup_dangling_step(self):
        self.seat(1, "A", SOLVE_R1)
        self.seat(1, "B", SOLVE_R1_RESULT)
        self.ledger(1, "solve-r1")
        bad = SOLVE_FOLLOWUP.replace("A-S2: The ten-day", "A-S9: The ten-day")
        self.seat(2, "A", bad)
        code, out = self.ledger(2, "solve-followup")
        self.assertEqual(code, 1)
        self.assertIn("dangling: leg-1 round 2: A cites A-S9", out)

    def test_solve_replaces_unknown_step_is_dangling(self):
        self.seat(1, "A", SOLVE_R1)
        self.ledger(1, "solve-r1")
        bad = SOLVE_FOLLOWUP.replace("[replaces: A-S2]", "[replaces: A-S9]")
        bad = bad.replace("B-PLAN", "A-PLAN").replace("B-S2", "A-S2")
        self.seat(2, "A", bad)
        code, out = self.ledger(2, "solve-followup")
        self.assertEqual(code, 1, out)
        self.assertIn("dangling: leg-1 round 2: A cites A-S9", out)

    def test_rerun_after_force_ignores_archived_versions(self):
        self.seat(1, "A", BRAINSTORM_R1)
        self.ledger(1, "brainstorm-r1")
        self.seat(1, "A.v1", BRAINSTORM_R1)
        self.seat(1, "A", BRAINSTORM_R1.replace("Quiet hour", "Silent hour"))
        self.assertEqual(self.ledger(1, "brainstorm-r1")[0], 0)
        self.assertEqual([i["id"] for i in self.items()],
                         ["A-I1", "A-I2", "A-I3", "A-I4", "A-WILDCARD"])
        self.assertIn("Silent hour", self.ledger_md())


if __name__ == "__main__":
    unittest.main()
